#!/usr/bin/env python2.6

from lxml import etree
import sys

xpath = sys.argv[1]  
filename = sys.argv[2] 

#xpath = "//y:NodeLabel"
#filename = "wants 2.graphml"

doc = etree.parse( filename )
r = doc.xpath(xpath,
			  namespaces={'y': "http://www.yworks.com/xml/graphml"})

assert(len(r)>0)

for n in r:
	print n.text, ",", n